### PR TITLE
including references of light extinction coefficient and fixing equation

### PR DESCRIPTION
**Pull request by arnaldorusso**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@arnaldorusso Do you have a test for that function?  It can be the paper values or any known values.  I am planning to run doctest on travis-ci for the package.

**Comment by arnaldorusso** [comment]
For sure Filipe. I'll write a simple test for all functions I have included
ASAP.
 Em 27/02/2015 13:10, "Filipe" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
@arnaldorusso Travis-CI is [working now](https://travis-ci.org/pyoceans/python-oceans/jobs/52738404).  Just add the docstring and push to this PR to run the tests.

**Comment by arnaldorusso** [comment]
The data included inside function should be moved to another directory?

**Comment by ocefpaf** [comment]
Nope.  It is fine where it is.  Let me see if `py.test` will find that automatically or no.  If not, I will fix it later in another PR.

**Pull request merged**
